export const WG_THEME_REQUEST = 'WG_THEME_REQUEST'
export const WG_THEME_ERROR = 'WG_THEME_ERROR'
export const WG_THEME_SUCCESS = 'WG_THEME_SUCCESS'
export const WG_THEME_SET_CSS_PROP = 'WG_THEME_SET_CSS_PROP'
