export const WG_UI_THEMES_REQUEST = 'WG_UI_THEMES_REQUEST'
export const WG_UI_THEMES_ERROR = 'WG_UI_THEMES_ERROR'
export const WG_UI_THEMES_SUCCESS = 'WG_UI_THEMES_SUCCESS'
export const WG_UI_SET_THEME_CSS = 'WG_UI_SET_THEME_CSS'
